export const ALLOWED_BLOCKS = {
  two: {
    half: [
      "acf/text",
      "acf/text-panel",
      "acf/offset-image",
      "core/image",
      "acf/infocard",
      "acf/feature-card",
      "acf/accordion",
      "acf/logo-showcase",
      "acf/blog-slider",
      "acf/video",
      "acf/form",
    ],
    small: [
      "acf/text",
      "core/image",
      "acf/servicecard",
      "acf/infocard",
      "acf/feature-card",
      "acf/accordion",
      "acf/logo-showcase",
      "acf/blog-slider",
      "acf/video",
    ],
    extraSmall: [
      "acf/text",
      "core/image",
      "acf/servicecard",
      "acf/infocard",
      "acf/feature-card",
      "acf/accordion",
      "acf/video",
    ],
  },
  twoColumnsEqual: [
    "acf/text",
    "core/image",
    "acf/offset-image",
    "acf/servicecard",
    "acf/infocard",
    "acf/feature-card",
    "acf/accordion",
    "acf/logo-showcase",
    "acf/blog-slider",
    "acf/video",
    "acf/form",
    "acf/location",
  ],
  three: [
    "acf/text",
    "core/image",
    "acf/servicecard",
    "acf/infocard",
    "acf/feature-card",
    "acf/accordion",
    "acf/video",
  ],
  four: [
    "acf/text",
    "core/image",
    "acf/servicecard",
    "acf/infocard",
    "acf/feature-card",
    "acf/accordion",
    "acf/video",
  ],
  six: ["acf/text", "core/image", "acf/feature-card"],
};

export const BLOCK_TITLES = {
  "core/columns": "Columns layout",
  "core/column": "Column",
};
