const childThemePath =
  "./wp-content/themes/" +
  (process.env.CHILD_THEME_FOLDER || "vdigital-wp-child-theme");
const colors = require("tailwindcss/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "tw-",
  content: [childThemePath + "/**/*.php", childThemePath + "/**/*.js"],
  theme: {
    fontFamily: {
      'jakarta': ['"Plus Jakarta Sans"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      'dm-sans': ['"DM Sans"', 'sans-serif'],
      'syne': ['"Syne"', 'sans-serif'],
      'big-shoulders': ['"Big Shoulders Display"', 'sans-serif'],
    },
    extend: {
      screens: {
        sm: "376px",
        container: "1512px",
        "3xl": "1921px",
      },
      fontSize: {
        sm: ["14px", "1.2"],
        base: ["16px", "1.2"],
        lg: ["18px", "1.2"],
        xl: ["20px", "1.2"],
        "3-1/2xl": "2rem",
        "mobile-title": ["32px", "36px"],
      },
      maxWidth: {
        mdlg: "29.375rem",
        "5-1/2xl": "66.75rem",
      },
      borderRadius: {
        "4xl": "2.5rem",
      },
      height: {
        15: "3.75rem",
      },
      padding: {
        15: "3.75rem",
        17: "4.375rem",
        29: "7.188rem",
        41: "10.313rem",
        50: "12.5rem",
        71: "17.813rem",
        75: "19rem",
      },
    },
    colors: {
      ...colors,
      primary: "#004ca8",
      turquoise: "#007D7D",
      spring: "#32aa00",
      core: {
        DEFAULT: "#081328",
        20: "rgba(8, 19, 40, 0.2)",
        50: "rgba(8, 19, 40, 0.5)",
        80: "rgba(8, 19, 40, 0.8)",
      },
      shade: "#212b3e",
      mist: "#526fa6",
      horizon: "#f1f2ff",
      edge: {
        DEFAULT: "#0195E8",
        hover: "#0376B8",
      },
      sky: "#0195E8",
      growth: {
        DEFAULT: "#44ac17",
        hover: "#2C6F1E",
      },
      focus: {
        DEFAULT: "#ffffff",
        50: "rgba(255, 255, 255, 0.5)",
        60: "rgba(255, 255, 255, 0.6)",
        70: "rgba(255, 255, 255, 0.7)",
      },
      warning: "#dc012d",
      teal: {
        DEFAULT: "#015971",
        hover: "#043D54",
      },
      forest: {
        DEFAULT: "#048B4E",
        hover: "#055B3F",
      },
      cobalt: {
        DEFAULT: "#01289E",
        hover: "#04206F",
      },

      // Old
      gray: {
        ...colors.gray,
        "01": "#EFF4F6",
        "02": "#5A6872",
        "03": "#8897A2",
        "04": "#EEF0F0",
        "05": "#434343",
        lighter: "#DFE3E6",
        black: "#152935",
      },
      blue: {
        ...colors.blue,
        "01": "#004ca8",
        "02": "#073f80",
        "03": "#00284b",
        "04": "#008CDC",
        "05": "rgba(0, 40, 75, 0.9)",
        "06": "#21385b",
      },
      green: {
        ...colors.green,
        "01": "#32aa00",
        "02": "#329d03",
        "03": "#EAF6E5",
        "04": "#96C800",
      },
      black: {
        "00": colors.black,
        "01": "#152935",
      },
      red: {
        "01": "#D30101",
        "03": "#FBE5E5",
      },
      yellow: {
        "01": "#FFD800",
      },
    },
  },
  safelist: [
    "!tw-pl-0",

    "tw-pt-2",
    "tw-pb-2",
    "tw-px-2",
    "sm:tw-pt-2",
    "sm:tw-pb-2",
    "sm:tw-px-2",
    "md:tw-pt-2",
    "md:tw-pb-2",
    "md:tw-px-2",
    "lg:tw-pt-2",
    "lg:tw-pb-2",
    "lg:tw-px-2",

    "tw-pt-4",
    "tw-pb-4",
    "tw-px-4",
    "sm:tw-pt-4",
    "sm:tw-pb-4",
    "sm:tw-px-4",
    "md:tw-pt-4",
    "md:tw-pb-4",
    "md:tw-px-4",
    "lg:tw-pt-4",
    "lg:tw-pb-4",
    "lg:tw-px-4",

    "tw-pt-8",
    "tw-pb-8",
    "tw-px-8",
    "sm:tw-pt-8",
    "sm:tw-pb-8",
    "sm:tw-px-8",
    "md:tw-pt-8",
    "md:tw-pb-8",
    "md:tw-px-8",
    "lg:tw-pt-8",
    "lg:tw-pb-8",
    "lg:tw-px-8",

    "tw-pt-11",
    "tw-pb-11",
    "tw-px-11",
    "sm:tw-pt-11",
    "sm:tw-pb-11",
    "sm:tw-px-11",
    "md:tw-pt-11",
    "md:tw-pb-11",
    "md:tw-px-11",
    "lg:tw-pt-11",
    "lg:tw-pb-11",
    "lg:tw-px-11",

    "tw-pt-12",
    "tw-pb-12",
    "tw-px-12",
    "sm:tw-pt-12",
    "sm:tw-pb-12",
    "sm:tw-px-12",
    "md:tw-pt-12",
    "md:tw-pb-12",
    "md:tw-px-12",
    "lg:tw-pt-12",
    "lg:tw-pb-12",
    "lg:tw-px-12",

    "tw-pt-17",
    "tw-pb-17",
    "tw-px-17",
    "sm:tw-pt-17",
    "sm:tw-pb-17",
    "sm:tw-px-17",
    "md:tw-pt-17",
    "md:tw-pb-17",
    "md:tw-px-17",
    "lg:tw-pt-17",
    "lg:tw-pb-17",
    "lg:tw-px-17",

    "tw-pt-20",
    "tw-pb-20",
    "tw-px-20",
    "sm:tw-pt-20",
    "sm:tw-pb-20",
    "sm:tw-px-20",
    "md:tw-pt-20",
    "md:tw-pb-20",
    "md:tw-px-20",
    "lg:tw-pt-20",
    "lg:tw-pb-20",
    "lg:tw-px-20",

    "tw-pt-24",
    "tw-pb-24",
    "tw-px-24",
    "sm:tw-pt-24",
    "sm:tw-pb-24",
    "sm:tw-px-24",
    "md:tw-pt-24",
    "md:tw-pb-24",
    "md:tw-px-24",
    "lg:tw-pt-24",
    "lg:tw-pb-24",
    "lg:tw-px-24",

    "tw-pt-29",
    "tw-pb-29",
    "tw-px-29",
    "sm:tw-pt-29",
    "sm:tw-pb-29",
    "sm:tw-px-29",
    "md:tw-pt-29",
    "md:tw-pb-29",
    "md:tw-px-29",
    "lg:tw-pt-29",
    "lg:tw-pb-29",
    "lg:tw-px-29",

    "tw-pt-32",
    "tw-pb-32",
    "tw-px-32",
    "sm:tw-pt-32",
    "sm:tw-pb-32",
    "sm:tw-px-32",
    "md:tw-pt-32",
    "md:tw-pb-32",
    "md:tw-px-32",
    "lg:tw-pt-32",
    "lg:tw-pb-32",
    "lg:tw-px-32",

    "tw-pt-36",
    "tw-pb-36",
    "tw-px-36",
    "sm:tw-pt-36",
    "sm:tw-pb-32",
    "sm:tw-px-32",
    "md:tw-pt-36",
    "md:tw-pb-32",
    "md:tw-px-32",
    "lg:tw-pt-36",
    "lg:tw-pb-32",
    "lg:tw-px-32",

    "tw-pt-41",
    "tw-pb-41",
    "tw-px-41",
    "sm:tw-pt-41",
    "sm:tw-pb-41",
    "sm:tw-px-41",
    "md:tw-pt-41",
    "md:tw-pb-41",
    "md:tw-px-41",
    "lg:tw-pt-41",
    "lg:tw-pb-41",
    "lg:tw-px-41",

    "tw-pt-50",
    "tw-pb-50",
    "tw-px-50",
    "sm:tw-pt-50",
    "sm:tw-pb-50",
    "sm:tw-px-50",
    "md:tw-pt-50",
    "md:tw-pb-50",
    "md:tw-px-50",
    "lg:tw-pt-50",
    "lg:tw-pb-50",
    "lg:tw-px-50",

    "tw-pt-71",
    "tw-pb-71",
    "tw-px-71",
    "sm:tw-pt-71",
    "sm:tw-pb-71",
    "sm:tw-px-71",
    "md:tw-pt-71",
    "md:tw-pb-71",
    "md:tw-px-71",
    "lg:tw-pt-71",
    "lg:tw-pb-71",
    "lg:tw-px-71",

    "tw-pt-75",
    "tw-pb-75",
    "tw-px-75",
    "sm:tw-pt-75",
    "sm:tw-pb-75",
    "sm:tw-px-75",
    "md:tw-pt-75",
    "md:tw-pb-75",
    "md:tw-px-75",
    "lg:tw-pt-75",
    "lg:tw-pb-75",
    "lg:tw-px-75",

    "tw-pt-0",
    "tw-pb-0",
    "tw-px-0",
    "sm:tw-pt-0",
    "sm:tw-pb-0",
    "sm:tw-px-0",
    "md:tw-pt-0",
    "md:tw-pb-0",
    "md:tw-px-0",
    "lg:tw-pt-0",
    "lg:tw-pb-0",
    "lg:tw-px-0",

    "tw-mt-3",
    "tw-mb-3",
    "tw-mx-3",
    "sm:tw-mt-3",
    "sm:tw-mb-3",
    "sm:tw-mx-3",
    "md:tw-mt-3",
    "md:tw-mb-3",
    "md:tw-mx-3",
    "lg:tw-mt-3",
    "lg:tw-mb-3",
    "lg:tw-mx-3",

    "tw-mt-6",
    "tw-mb-6",
    "tw-mx-6",
    "sm:tw-mt-6",
    "sm:tw-mb-6",
    "sm:tw-mx-6",
    "md:tw-mt-6",
    "md:tw-mb-6",
    "md:tw-mx-6",
    "lg:tw-mt-6",
    "lg:tw-mb-6",
    "lg:tw-mx-6",

    "tw-mt-24",
    "tw-mb-24",
    "tw-mx-24",
    "sm:tw-mt-24",
    "sm:tw-mb-24",
    "sm:tw-mx-24",
    "md:tw-mt-24",
    "md:tw-mb-24",
    "md:tw-mx-24",
    "lg:tw-mt-24",
    "lg:tw-mb-24",
    "lg:tw-mx-24",

    "tw-mt-0",
    "tw-mb-0",
    "tw-mx-0",
    "sm:tw-mt-0",
    "sm:tw-mb-0",
    "sm:tw-mx-0",
    "md:tw-mt-0",
    "md:tw-mb-0",
    "md:tw-mx-0",
    "lg:tw-mt-0",
    "lg:tw-mb-0",
    "lg:tw-mx-0",

    "tw-h-20",
    "sm:tw-h-20",
    "md:tw-h-20",
    "lg:tw-h-20",
    "tw-h-32",
    "sm:tw-h-32",
    "md:tw-h-32",
    "lg:tw-h-32",
    "tw-h-64",
    "sm:tw-h-64",
    "md:tw-h-64",
    "lg:tw-h-64",

    "tw-max-w-24",

    "tw-border-gray-lighter",
    "tw-border-blue-01",
    "tw-border-dashed",
    "tw-border-solid",
    "tw-transition-all",
    "tw-duration-300",
    "tw-bg-blue-04",
    "tw-bg-green-01",
    "tw-bg-green-04",
    "tw-bg-blue-01",
    "tw-bg-primary",
    "tw-bg-turquoise",

    "tw-text-blue-04",
    "tw-text-turquoise",
    "tw-text-green-01",
    "tw-text-blue-01",
    "tw-text-primary",

    "hover:tw-text-blue-04",
    "hover:tw-text-turquoise",
    "hover:tw-text-green-01",
    "hover:tw-text-blue-01",
    "hover:tw-text-primary",

    "tw-bg-blue-04",
    "tw-bg-turquoise",
    "tw-bg-green-01",
    "tw-bg-blue-01",
    "tw-bg-primary",

    "hover:tw-bg-blue-04",
    "hover:tw-bg-turquoise",
    "hover:tw-bg-green-01",
    "hover:tw-bg-blue-01",
    "hover:tw-bg-primary",

    "tw-border-blue-04",
    "tw-border-turquoise",
    "tw-border-green-01",
    "tw-border-blue-01",
    "tw-border-primary",

    "tw-aspect-video",

    "tw-underline-offset-10",

    "tw-decoration-growth",
    "tw-decoration-forest",
    "tw-decoration-teal",
    "tw-decoration-cobalt",
  ],
  plugins: [],
};
